services:
  - type: worker
    name: youtube-stream-worker
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: YOUTUBE_STREAM_KEY
        sync: false
